# Generated by Django 4.2.7 on 2025-09-20 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='missing_persons/')),
                ('last_seen_date', models.DateTimeField()),
                ('last_seen_location', models.CharField(max_length=300)),
                ('contact_info', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('missing_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='missing_persons.missingperson')),
            ],
        ),
    ]
